easy_admin:
    site_name: 'VIR - Gestion du parc'
    design:
        menu:
            # - { label: 'Les utilisateurs', entity: 'Users'}
            #  - { label: 'Commandes', entity: 'Orders'}
            - { label: 'Famille de produit', entity: 'Type_colis'}
            - { label: 'Statut du colis', entity: 'Status_Label'}
            - { label: 'Type de retours', entity: 'Type_retours'}
            - { label: "Donneur d'ordres", entity: 'Companies'}
            - { label: 'Agences', entity: 'Agencies'}
            - { label: 'Satut des commandes', entity: 'Order_statut'}
            - { label: "Retour à l'appli", route: 'index' }
    entities:
        # List the entity class name you want to manage
     #   Orders:
     #       class: App\Entity\Orders

        Companies:
            class: App\Entity\Companies
            form:
                fields:
                    - { property: 'name', type: 'text' }
                    - { property: 'enable', type: 'checkbox' }

        Agencies:
            class: App\Entity\Agencies
            form:
                fields:
                    - { property: 'name', type: 'text' }
                    - { property: 'enable', type: 'checkbox' }

     #   Users:
     #       class: App\Entity\Users
     #       password_encoding: { algorithm: 'bcrypt', cost: 12 }
#
     #       form:
     #           fields:
     #               - { property: 'LastName', type: 'text' }
     #               - { property: 'FirstName', type: 'text' }
     #               - { property: 'FirstName', type: 'text' }
     #               #- { property: 'Agency', type: 'choice'}
     #               - { property: 'Agency', type: 'entity', type_options: { class: 'App\Entity\Agencies' } }
     #               - { property: 'username', type: 'text'}
     #              # - { property: 'password', type: 'repeated', type_options: { type: 'Symfony\Component\Form\Extension\Core\Type\PasswordType', first_options: {label: 'Mot de passe'}, second_options: {label: 'Confirmation Mot de passe'}, invalid_message: 'Les mots de passe ne correspondent pas.'}}
     #               #- { property: 'password', type: 'password' }
     #               - { property: 'Account', type: 'checkbox' }
     #               - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

        Type_colis:
            class: App\Entity\FamilyProduct
            form:
                fields:
                    - { property: 'name', type: 'text' }
        Status_Label:
                    class: App\Entity\LabelStatus
                    form:
                        fields:
                            - { property: 'name', type: 'text' }
                            - { property: 'enable', type: 'checkbox' }

        Type_retours:
            class: App\Entity\OrderBack
            form:
                fields:
                    - { property: 'name', type: 'text' }
                    - { property: 'Status', type: 'checkbox' }

        Order_statut:
            class: App\Entity\OrderStatus
            form:
                fields:
                    - { property: 'name', type: 'text' }
                    - { property: 'enable', type: 'checkbox' }