easy_admin:
    site_name: 'VIR - Gestion du parc'
    design:
        menu:
            - { label: 'Les utilisateurs', entity: 'Users'}
            - { label: 'Famille de produit', entity: 'Type_colis'}
            - { label: "Retour à l'appli", route: 'index' }
    entities:
        # List the entity class name you want to manage

        Users:
            class: App\Entity\Users
            form:
                fields:
                    - { property: 'LastName', type: 'text' }
                    - { property: 'FirstName', type: 'text' }
                    - { property: 'Email', type: 'email' }
                    - { property: 'Username', type: 'text' }
                    - { property: 'password', type: 'password' }
                    - { property: 'Account', type: 'checkbox' }

        Type_colis:
            class: App\Entity\FamilyProduct
            form:
                fields:
                    - { property: 'name', type: 'text' }

